name: Label Change Comment Bot

on:
  issues:
    types: [unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Check for Severity Labels
      if: |
        github.event.label.name == 'Severity-1' ||
        github.event.label.name == 'Severity-2' ||
        github.event.label.name == 'Severity-3' ||
        github.event.label.name == 'Severity-4'
      run: |
        echo "Severity label removed: ${{ github.event.label.name }}"
        curl -X POST -H "Authorization: token ${{ secrets.Gh_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -d '{"body":"@quamrulsiddiqui The label ${{ github.event.label.name }} was updated. Please update the same in the Project board by [github-actions[bot]]."}' \
        ${{ github.event.issue.url }}/comments
